# Generated by Django 5.0.2 on 2024-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entidade', models.CharField(max_length=100)),
                ('num_servico', models.CharField(max_length=100)),
                ('num_estacao', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tecnologia', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('azimute', models.CharField(max_length=100)),
                ('altura_antena', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
